name: Game Update Runner

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  check-tf2-build:
    runs-on: self-hosted
    outputs:
      changed: ${{ steps.check.outputs.changed }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup SteamCMD
        uses: CyberAndrii/setup-steamcmd@v1

      - name: Restore previous build ID from cache
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: build-id.txt
          key: tf2-build-${{ github.repository }}

      - name: Check TF2 build and trigger if changed
        id: check
        run: |
          # Get current build ID
          steamcmd +login anonymous +app_info_print 232250 +quit | grep -A 5 '"public"' | grep '"buildid"' | sed 's/.*"buildid"[[:space:]]*"\([^"]*\)".*/\1/' > current.txt
          CURR=$(cat current.txt)
          
          PREV=""
          [ -f "build-id.txt" ] && PREV=$(cat build-id.txt)
          
          if [ "$CURR" != "$PREV" ] && [ -n "$CURR" ]; then
            echo "Build changed! Will trigger Docker build..."
            
            # Save new build ID for next run
            echo "$CURR" > build-id.txt
            echo "changed=true" >> $GITHUB_OUTPUT
            
            echo "Build ID changed to $CURR"
          else
            echo "No new build change detected"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Save build ID to cache
        uses: actions/cache/save@v3
        if: always()
        with:
          path: build-id.txt
          key: tf2-build-${{ github.repository }}-${{ github.run_id }}

  build-tf2-comp:
    needs: check-tf2-build
    if: needs.check-tf2-build.outputs.changed == 'true'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Trigger COMP Build
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.COMP_RUNNER_GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/push-prod.yaml/dispatches \
            -d '{"ref":"main"}'

  build-tf2-mge:
    needs: check-tf2-build
    if: needs.check-tf2-build.outputs.changed == 'true'
    runs-on: self-hosted
    steps:
      - name: Trigger MGE Build
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.MGE_RUNNER_GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/avanavan/docker-tf2mge/dispatches \
            -d '{
              "event_type": "build",
              "client_payload": {
                "source": "tf2-build-checker",
                "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'",
                "repository": "${{ github.repository }}"
              }
            }'
  
    